### ISSUE TITLE
Any news regarding the patent?

### ISSUE THREAD

**Issue by dumblob** [mightycow/Sluggish#1]
In Readme is mentioned, that there is an ongoing patent application. Do you happen to have any news on that? In which countries in the world was the patent request submitted?

I'd like to use this implementation (or at least get some inspiration) e.g. in [Nuklear](https://github.com/vurtun/nuklear ) or [gg](https://github.com/vlang/gg ), but am afraid of patents :cry:.

**Comment by mightycow** [comment]
A patent application was filed in the USA (February 1, 2018) and recently granted (August 6, 2019). You can look in the USPTO database for "Method for rendering resolution-independent shapes directly from outline control points". As for other countries, I do not know. You should definitely not be using this if you intend to redistribute your work.

Now, there are many alternatives whose viability will greatly vary based on your tech/performance/quality/legal needs:
- nVidia's path rendering OpenGL extension:
https://www.khronos.org/registry/OpenGL/extensions/NV/NV_path_rendering.txt
- Multi-channel signed distance fields:
https://github.com/Chlumsky/msdfgen/files/3050967/thesis.pdf
- 16xAA font rendering with coverage masks:
https://www.superluminal.eu/2018/10/29/16xaa-font-rendering-using-coverage-masks-part-i/
- Real-Time Analytic Antialiased Text for 3-D Environments:
https://www.highperformancegraphics.org/wp-content/uploads/2019/session1/real-time_analytic_antialiased_text.pdf
- Patrick Walton's Pathfinder:
https://nical.github.io/posts/a-look-at-pathfinder.html

I came across a few others but they didn't look as interesting.

**Comment by dumblob** [comment]
Wow, thanks for the thorough answer! I'll take a look which of those "alternatives" are easier to implement or have wider cross-platform potential.

**Comment by mightycow** [comment]
As of March 17 2026, Eric Lengyel announced that he is "permanently and irrevocably dedicating the Slug patent to the public domain". He also wrote that "anybody can freely implement the Slug algorithm from this day forward without a license for whatever purpose they want, and they don’t need to worry about infringing upon any intellectual property rights." For more details on the legalese of that change, refer to:  
https://terathon.com/blog/decade-slug.html
